### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by ThatLurker**
Changed all the domains to the new ones and added command that uses the autogen feature to example

### CODE REVIEW

**Comment by wileyyugioh** [comment]
Everything looks good except that KissAsian uses /Drama/, not /DramaList/! Change it and I'll merge.

**Comment by ThatLurker** [comment]
i think they also changed it to /DramaList format.

**Comment by wileyyugioh** [comment]
Can you post an example? The only /DramaList/ I can find is the master list for all of the shows, not just one individual one.

**Comment by ThatLurker** [comment]
when i go to http://kissasian.com/Drama/ it redirects to the error page.

**Comment by wileyyugioh** [comment]
Yes, but look at http://kissasian.com/Drama/Rakuen for example. The script only downloads one show, not all the shows at once. /DramaList/ is used for all shows. /Drama/ is used for only one.

**Comment by ThatLurker** [comment]
ou now i get it, sorry took me a while to notice that 😄.

yeah i will edit it right now.

**Pull request merged**
